name: Release General

on:
  release:
    types:
      - created

jobs:
  publish-release-artifacts:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout tree ...
        uses: actions/checkout@v2
      - name: Check build ...
        run: make
      - name: Build release ...
        run: make release
      - name: Upload artifacts ...
        uses: skx/github-action-publish-binaries@release-0.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args:
            - ../*.tar.bz2
            - ../*.md5
            - ../*.sha256
